image: node:18

stages:
  - install
  - lint
  - pages

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  script:
    - npm run lint
  dependencies:
    - install
      

pages:
  stage: pages
  script: npm run build
  artifacts:
    paths:
      - public
  dependencies:
    - install