image: node:18

stages:
  - install
  - lint
  - build
  - deploy

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  script:
    - npm run lint
  dependencies:
    - install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - public/
  dependencies:
    - install
      
pages:
  stage: deploy
  script: 
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public
  dependencies:
    - build